CREATE TYPE organization_status as ENUM ('PENDING', 'ACTIVE', 'DISABLED', 'DELETED');
CREATE TYPE organization_type as ENUM ('PLATFORM', 'BUYER', 'SELLER');

CREATE TABLE organizations
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization_id UUID                           UNIQUE   NOT NULL,
    name_en         VARCHAR(255)                   UNIQUE   NOT NULL,
    name_ar         VARCHAR(255)                   UNIQUE   NOT NULL,
    slug            VARCHAR(255)                   UNIQUE   NOT NULL,
    industry        VARCHAR(255)                            NOT NULL,
    type            organization_type                       NOT NULL,
    status          organization_status                     NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE                NOT NULL DEFAULT NOW(),
    update_at       TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_organizations PRIMARY KEY (id)
);

CREATE INDEX idx_organization_id            ON organizations(organization_id);
CREATE INDEX idx_organization_status        ON organizations(status);
CREATE INDEX idx_organization_type          ON organizations(type);
CREATE INDEX idx_organization_created_at    ON organizations(created_at);