// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/products": {
    params: {};
  };
  "/dashboard/orders": {
    params: {};
  };
  "/dashboard/campaigns": {
    params: {};
  };
  "/dashboard/analytics": {
    params: {};
  };
  "/dashboard/buyers": {
    params: {};
  };
  "/dashboard/messages": {
    params: {};
  };
  "/dashboard/settings": {
    params: {};
  };
  "/dashboard/procurement": {
    params: {};
  };
  "/dashboard/suppliers": {
    params: {};
  };
  "/dashboard/team": {
    params: {};
  };
  "/dashboard/users": {
    params: {};
  };
  "/dashboard/organizations": {
    params: {};
  };
  "/dashboard/system-settings": {
    params: {};
  };
  "/dashboard/reports": {
    params: {};
  };
  "/dashboard/moderation": {
    params: {};
  };
  "/dashboard/communications": {
    params: {};
  };
  "/dashboard/configuration": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/register" | "/dashboard" | "/dashboard/products" | "/dashboard/orders" | "/dashboard/campaigns" | "/dashboard/analytics" | "/dashboard/buyers" | "/dashboard/messages" | "/dashboard/settings" | "/dashboard/procurement" | "/dashboard/suppliers" | "/dashboard/team" | "/dashboard/users" | "/dashboard/organizations" | "/dashboard/system-settings" | "/dashboard/reports" | "/dashboard/moderation" | "/dashboard/communications" | "/dashboard/configuration";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "routes/dashboard/layout.tsx": {
    id: "routes/dashboard/layout";
    page: "/dashboard" | "/dashboard/products" | "/dashboard/orders" | "/dashboard/campaigns" | "/dashboard/analytics" | "/dashboard/buyers" | "/dashboard/messages" | "/dashboard/settings" | "/dashboard/procurement" | "/dashboard/suppliers" | "/dashboard/team" | "/dashboard/users" | "/dashboard/organizations" | "/dashboard/system-settings" | "/dashboard/reports" | "/dashboard/moderation" | "/dashboard/communications" | "/dashboard/configuration";
  };
  "routes/dashboard/index.tsx": {
    id: "routes/dashboard/index";
    page: "/dashboard" | "/dashboard/products" | "/dashboard/orders" | "/dashboard/campaigns" | "/dashboard/analytics" | "/dashboard/buyers" | "/dashboard/messages" | "/dashboard/settings" | "/dashboard/procurement" | "/dashboard/suppliers" | "/dashboard/team" | "/dashboard/users" | "/dashboard/organizations" | "/dashboard/system-settings" | "/dashboard/reports" | "/dashboard/moderation" | "/dashboard/communications" | "/dashboard/configuration";
  };
  "routes/dashboard/products/index.tsx": {
    id: "routes/dashboard/products/index";
    page: "/dashboard/products";
  };
  "routes/dashboard/orders/index.tsx": {
    id: "routes/dashboard/orders/index";
    page: "/dashboard/orders";
  };
  "routes/dashboard/campaigns/index.tsx": {
    id: "routes/dashboard/campaigns/index";
    page: "/dashboard/campaigns";
  };
  "routes/dashboard/analytics/index.tsx": {
    id: "routes/dashboard/analytics/index";
    page: "/dashboard/analytics";
  };
  "routes/dashboard/buyers/index.tsx": {
    id: "routes/dashboard/buyers/index";
    page: "/dashboard/buyers";
  };
  "routes/dashboard/messages/index.tsx": {
    id: "routes/dashboard/messages/index";
    page: "/dashboard/messages";
  };
  "routes/dashboard/settings/index.tsx": {
    id: "routes/dashboard/settings/index";
    page: "/dashboard/settings";
  };
  "routes/dashboard/procurement/index.tsx": {
    id: "routes/dashboard/procurement/index";
    page: "/dashboard/procurement";
  };
  "routes/dashboard/suppliers/index.tsx": {
    id: "routes/dashboard/suppliers/index";
    page: "/dashboard/suppliers";
  };
  "routes/dashboard/team/index.tsx": {
    id: "routes/dashboard/team/index";
    page: "/dashboard/team";
  };
  "routes/dashboard/users/index.tsx": {
    id: "routes/dashboard/users/index";
    page: "/dashboard/users";
  };
  "routes/dashboard/organizations/index.tsx": {
    id: "routes/dashboard/organizations/index";
    page: "/dashboard/organizations";
  };
  "routes/dashboard/system-settings/index.tsx": {
    id: "routes/dashboard/system-settings/index";
    page: "/dashboard/system-settings";
  };
  "routes/dashboard/reports/index.tsx": {
    id: "routes/dashboard/reports/index";
    page: "/dashboard/reports";
  };
  "routes/dashboard/moderation/index.tsx": {
    id: "routes/dashboard/moderation/index";
    page: "/dashboard/moderation";
  };
  "routes/dashboard/communications/index.tsx": {
    id: "routes/dashboard/communications/index";
    page: "/dashboard/communications";
  };
  "routes/dashboard/configuration/index.tsx": {
    id: "routes/dashboard/configuration/index";
    page: "/dashboard/configuration";
  };
};